name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci --ignore-scripts
    - run: echo "$PWD/node_modules/.bin" >> "$GITHUB_PATH"
    - run: deno cache --no-npm src/cli.ts
    - run: deno lint

    - run: src/cli.ts
    - run: lib/cli.js --outDir nodejs/
    - run: git diff --no-index lib/ nodejs/

    - run: deno test --allow-read=.
    - run: fdt lib/**/*.test.js
