name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  id-token: write

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci --ignore-scripts
    - run: npm run prepare
    - name: Publish to npm
      run: |
        npm config set //registry.npmjs.org/:_authToken '${NPM_TOKEN}'
        [[ "$GITHUB_REF_NAME" =~ - ]] && npm config set tag=next
        npm pkg set version="${GITHUB_REF_NAME/v/}"
        npm publish --ignore-scripts
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        NPM_CONFIG_PROVENANCE: true
