name: Update

on:
  schedule:
    # 30 min after deno-bin
    - cron: '30 12 * * SAT'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # to trigger release workflow
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
      - name: git config
        run: |
          git config user.name 'GitHub Actions'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config user.signingKey '${{ secrets.SSH_DEPLOY_KEY }}'
          git config gpg.format ssh
      - run: npm ci --ignore-scripts
      - run: scripts/update.sh
        env:
          npm_config_sign_git_commit: true
          npm_config_sign_git_tag: true
      - run: git push --follow-tags
